apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app: echo
spec:
  type: ClusterIP
  selector:
    # Selecciona los objetos a los que se aplica
    app: echo
  ports:
    - port: 80
      protocol: TCP
