apiVersion: v1
kind: Service
metadata:
  name: mongo-microservice
  labels:
    app: mongo-microservice
spec:
  type: ClusterIP
  selector:
    # Selecciona los objetos a los que se aplica
    app: mongo-microservice
  ports:
    - port: 8080
      protocol: TCP
