apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
  selector:
    app: mongo

---

apiVersion: v1
data:
  MONGO_ADMIN: cm9vdA==
  MONGO_ADMIN_PASSWORD: cm9vdG1vbmdv
  MONGO_DB: ZGF0YWJhc2U=
  MONGO_PASSWORD: bW9uZ29wYXNzd29yZA==
  MONGO_USER: bW9uZ29hZG1pbg==
  MONGO_USER_ROLE: cmVhZFdyaXRl
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo # tiene que coincidir con .spec.template.metadata.labels
  serviceName: "mongo-service"
  template:
    metadata:
      labels:
        app: mongo # tiene que coincidir con .spec.selector.matchLabels
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_ADMIN
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ADMIN
          - name: MONGO_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ADMIN_PASSWORD
          - name: MONGO_DB
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_DB
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_USER
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_PASSWORD
          - name: MONGO_USER_ROLE
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_USER_ROLE

        volumeMounts:
        - name: mongo-pv
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-pv
    spec:
      storageClassName: almacenamiento.local
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
