apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql-port
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql # tiene que coincidir con .spec.template.metadata.labels
  serviceName: "mysql-service"
  template:
    metadata:
      labels:
        app: mysql # tiene que coincidir con .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: NeverDoThis
        - name: MYSQL_DATABASE
          value: bookstore
        - name: MYSQL_USER
          value: app_user
        - name: MYSQL_PASSWORD
          value: UseSecrets
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv
    spec:
      storageClassName: almacenamiento.local
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi