apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql-port
  selector:
    app: mysql

---

apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: TmV2ZXJEb1RoaXM=
  MYSQL_DATABASE: dHJhYmFqb2ZpbmFs
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: TmV2ZXJEb1RoaXM=
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql # tiene que coincidir con .spec.template.metadata.labels
  serviceName: "mysql-service"
  template:
    metadata:
      labels:
        app: mysql # tiene que coincidir con .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:latest
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          value: mysql-secret
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv
    spec:
      storageClassName: almacenamiento.local
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
