apiVersion: v1
kind: Service
metadata:
  name: consumidores-microservice
  labels:
    app: consumidores-microservice
spec:
  type: ClusterIP
  selector:
    # Selecciona los objetos a los que se aplica
    app: consumidores-microservice
  ports:
    - name: http
      port: 8080